services:
  mariadb:
    image: mariadb:10.5.12
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080
  
  


volumes:
  database: