name: Docker Image CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        working-directory: ./Backend
      - name: Build the Docker image
        run: docker build . --file Backend/Dockerfile --tag my-image-name:1.0.0
